// Generated by scripts/sync-packager-config.sh — do not edit by hand.
enum PackagerConfig {
  static let host = "192.168.1.116"
  static let port: UInt = 8081
  static let fallbackHosts = ["192.168.1.116", "Sammys-MacBook-Air.local", "localhost"]
}
