#!/usr/bin/env bash
# Create a no-op migration stub so remote schema_migrations stays in sync with git.
# Usage: ./supabase/scripts/generate_migration_stub.sh 20260608120000 products_stripe_price_ids
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
MIGRATIONS="$ROOT/supabase/migrations"

VERSION="${1:-}"
NAME="${2:-sync_stub}"

if [[ ! "$VERSION" =~ ^[0-9]{14}$ ]]; then
  echo "Usage: $0 <14_digit_version> [name_snippet]" >&2
  echo "Example: $0 20260608120000 products_stripe_price_ids" >&2
  exit 1
fi

TARGET="$MIGRATIONS/${VERSION}_${NAME}.sql"
if [[ -f "$TARGET" ]]; then
  echo "Already exists: $TARGET" >&2
  exit 1
fi

cat > "$TARGET" <<EOF
-- Migration already applied on remote; stub keeps git in sync with supabase_migrations.
-- Generated by supabase/scripts/generate_migration_stub.sh
select 1;
EOF

echo "Created $TARGET"
echo "Next: git add supabase/migrations && git commit && git push"
