#!/usr/bin/env bash
# Writes Metro host/port for the native iOS debug build and Expo bundler scripts.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
IOS_DIR="$ROOT/ios"
HOST="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"
BONJOUR="$(scutil --get LocalHostName 2>/dev/null).local"
PORT="${METRO_PORT:-8081}"
USB_DEVICE=0
if xcrun devicectl list devices 2>/dev/null | grep -q "connected"; then
  USB_DEVICE=1
fi

if [[ -z "$HOST" ]]; then
  echo "Warning: could not detect LAN IP (en0/en1)." >&2
  if [[ -f "$IOS_DIR/FutureTrace/PackagerConfig.swift" ]]; then
    HOST="$(sed -n 's/.*host = "\([^"]*\)".*/\1/p' "$IOS_DIR/FutureTrace/PackagerConfig.swift" | head -1)"
    echo "Keeping existing host: ${HOST:-unknown}" >&2
  fi
fi

if [[ -z "$HOST" ]]; then
  echo "Connect to Wi-Fi and rerun: npm run sync:packager" >&2
  exit 1
fi

# LAN IP + Bonjour (.local) + localhost (USB with iproxy only).
FALLBACK_HOSTS="\"$HOST\", \"$BONJOUR\", \"localhost\""

mkdir -p "$IOS_DIR/FutureTrace"

cat > "$IOS_DIR/FutureTrace/PackagerConfig.swift" <<EOF
// Generated by scripts/sync-packager-config.sh — do not edit by hand.
enum PackagerConfig {
  static let host = "$HOST"
  static let port: UInt = $PORT
  static let fallbackHosts = [$FALLBACK_HOSTS]
}
EOF

cat > "$IOS_DIR/.xcode.env.local" <<EOF
export REACT_NATIVE_PACKAGER_HOSTNAME=$HOST
export RCT_METRO_PORT=$PORT
export SKIP_BUNDLING=1
EOF

echo "Packager config → $HOST:$PORT"
