import type { OnetOccupation } from "./types";

/**
 * Curated O*NET-style occupation snapshots for offline / fallback matching.
 * SOC codes and task wording align with O*NET Online taxonomy.
 */
export const LOCAL_ONET_INDEX: OnetOccupation[] = [
  {
    code: "15-1252.00",
    title: "Software Developers",
    description: "Research, design, and develop computer and network software or specialized utility programs.",
    alternateTitles: ["Software Engineer", "Application Developer", "Full Stack Developer", "Backend Developer"],
    tasks: [
      "Modify existing software to correct errors or improve performance",
      "Develop and direct software system testing and validation procedures",
      "Analyze user needs and software requirements to determine feasibility of design",
      "Prepare reports or correspondence concerning project specifications",
      "Collaborate with stakeholders to define system architecture and requirements",
      "Write and maintain technical documentation for software systems",
      "Review code and provide technical guidance to development teams",
    ],
    skills: ["Programming", "Systems Analysis", "Critical Thinking", "Complex Problem Solving"],
    workActivities: ["Working with Computers", "Analyzing Data or Information", "Making Decisions and Solving Problems"],
  },
  {
    code: "15-2051.00",
    title: "Data Scientists",
    description: "Develop and implement a set of techniques or analytics applications to transform raw data into meaningful information.",
    alternateTitles: ["Machine Learning Engineer", "AI Engineer", "ML Engineer", "Data Analyst"],
    tasks: [
      "Analyze, manipulate, or process large sets of data using statistical software",
      "Design and validate predictive models and machine learning algorithms",
      "Prepare reports and visualizations to communicate analytical findings",
      "Collaborate with business stakeholders to define analytical objectives",
      "Document data pipelines and model assumptions for reproducibility",
      "Evaluate model performance and refine approaches based on results",
    ],
    skills: ["Mathematics", "Programming", "Critical Thinking", "Active Learning"],
    workActivities: ["Analyzing Data or Information", "Working with Computers", "Processing Information"],
  },
  {
    code: "43-6014.00",
    title: "Secretaries and Administrative Assistants",
    description: "Perform routine clerical and administrative functions such as drafting correspondence, scheduling appointments, and organizing files.",
    alternateTitles: ["Administrative Assistant", "Office Administrator", "Executive Assistant", "Salesforce Administrator", "CRM Administrator"],
    tasks: [
      "Schedule and confirm appointments for clients, customers, or supervisors",
      "Prepare invoices, reports, memos, letters, and other documents using word processing or spreadsheet software",
      "Maintain filing systems and update records with new information",
      "Answer telephones and direct calls to appropriate staff",
      "Perform data entry and routine database maintenance tasks",
      "Compile and organize paperwork for meetings and travel arrangements",
      "Process incoming and outgoing mail and email correspondence",
    ],
    skills: ["Active Listening", "Writing", "Time Management", "Coordination"],
    workActivities: ["Performing Administrative Activities", "Communicating with Supervisors", "Organizing, Planning, and Prioritizing Work"],
  },
  {
    code: "13-1111.00",
    title: "Management Analysts",
    description: "Conduct organizational studies and evaluations, design systems and procedures, and conduct workflow analyses.",
    alternateTitles: ["Business Analyst", "Operations Analyst", "Strategy Consultant", "Consultant"],
    tasks: [
      "Analyze data gathered and develop solutions or alternative methods of proceeding",
      "Document findings of study and prepare recommendations for implementation",
      "Confer with personnel concerned to ensure successful functioning of newly implemented systems",
      "Interview or survey workers to gather information about job duties and responsibilities",
      "Prepare manuals and train workers in use of new forms, reports, or procedures",
      "Develop and present reports to executive leadership on business performance",
      "Evaluate compliance with organizational policies and regulatory requirements",
    ],
    skills: ["Critical Thinking", "Active Listening", "Complex Problem Solving", "Judgment and Decision Making"],
    workActivities: ["Analyzing Data or Information", "Making Decisions and Solving Problems", "Communicating with Supervisors"],
  },
  {
    code: "13-1121.00",
    title: "Project Management Specialists",
    description: "Analyze and coordinate the schedule, timeline, and resources required to complete a project.",
    alternateTitles: ["Project Manager", "Program Manager", "Product Manager", "Technical Program Manager"],
    tasks: [
      "Monitor project milestones and deliverables to ensure timely completion",
      "Develop and manage project plans, schedules, and resource allocations",
      "Communicate project status and risks to stakeholders and leadership",
      "Coordinate cross-functional teams to resolve project issues",
      "Prepare status reports and documentation for project reviews",
      "Identify scope changes and assess impact on timeline and budget",
      "Facilitate meetings and decision-making among project stakeholders",
    ],
    skills: ["Coordination", "Management of Personnel Resources", "Critical Thinking", "Active Listening"],
    workActivities: ["Organizing, Planning, and Prioritizing Work", "Communicating with Supervisors", "Making Decisions and Solving Problems"],
  },
  {
    code: "43-4051.00",
    title: "Customer Service Representatives",
    description: "Interact with customers to provide basic or scripted information in response to routine inquiries about products and services.",
    alternateTitles: ["Customer Support Specialist", "Customer Success Representative", "Support Agent", "Help Desk"],
    tasks: [
      "Answer customer questions about products, services, or policies",
      "Resolve routine customer complaints or escalate complex issues",
      "Process orders, forms, applications, and requests according to scripts",
      "Maintain records of customer interactions and transactions",
      "Follow standard operating procedures for common support scenarios",
      "Refer customers to appropriate departments for specialized assistance",
      "Document troubleshooting steps and outcomes in ticketing systems",
    ],
    skills: ["Active Listening", "Speaking", "Service Orientation", "Social Perceptiveness"],
    workActivities: ["Communicating with People Outside the Organization", "Performing for or Working Directly with the Public", "Documenting/Recording Information"],
  },
  {
    code: "11-2021.00",
    title: "Marketing Managers",
    description: "Plan, direct, or coordinate marketing policies and programs to determine demand for products and services.",
    alternateTitles: ["Marketing Manager", "Brand Manager", "Growth Manager", "Digital Marketing Manager"],
    tasks: [
      "Develop pricing strategies and marketing campaigns for products or services",
      "Analyze market research data to identify customer segments and trends",
      "Collaborate with creative teams to develop promotional materials",
      "Monitor campaign performance and adjust strategies based on results",
      "Prepare reports on marketing activities, expenditures, and ROI",
      "Negotiate contracts with vendors and advertising agencies",
      "Present marketing plans and results to executive leadership",
    ],
    skills: ["Persuasion", "Critical Thinking", "Active Learning", "Judgment and Decision Making"],
    workActivities: ["Thinking Creatively", "Analyzing Data or Information", "Communicating with Supervisors"],
  },
  {
    code: "15-1299.08",
    title: "Computer Systems Engineers/Architects",
    description: "Design and develop solutions to complex application problems, system administration issues, or network concerns.",
    alternateTitles: ["Solutions Architect", "Systems Architect", "DevOps Engineer", "Platform Engineer", "SRE"],
    tasks: [
      "Design system architecture to meet scalability, security, and reliability requirements",
      "Evaluate emerging technologies for integration into existing systems",
      "Collaborate with development and operations teams on deployment strategies",
      "Document technical standards, patterns, and architecture decisions",
      "Troubleshoot complex production incidents and performance bottlenecks",
      "Review infrastructure designs and provide technical guidance",
    ],
    skills: ["Systems Analysis", "Complex Problem Solving", "Critical Thinking", "Technology Design"],
    workActivities: ["Working with Computers", "Making Decisions and Solving Problems", "Analyzing Data or Information"],
  },
  {
    code: "41-4011.00",
    title: "Sales Representatives, Wholesale and Manufacturing",
    description: "Sell goods for wholesalers or manufacturers to businesses or groups of individuals.",
    alternateTitles: ["Account Executive", "Sales Representative", "Business Development Representative", "RevOps Analyst"],
    tasks: [
      "Contact regular and prospective customers to demonstrate products and services",
      "Answer questions about products, prices, availability, and credit terms",
      "Prepare sales presentations and proposals for prospective clients",
      "Maintain records of sales, contacts, and follow-up activities in CRM systems",
      "Monitor market conditions and competitor activities",
      "Negotiate contracts and close sales with business customers",
      "Process routine sales orders and coordinate fulfillment logistics",
    ],
    skills: ["Persuasion", "Negotiation", "Active Listening", "Speaking"],
    workActivities: ["Selling or Influencing Others", "Communicating with People Outside the Organization", "Establishing and Maintaining Interpersonal Relationships"],
  },
  {
    code: "11-3021.00",
    title: "Computer and Information Systems Managers",
    description: "Plan, direct, or coordinate activities in fields such as electronic data processing, information systems, and computer programming.",
    alternateTitles: ["IT Manager", "Engineering Manager", "Director of Engineering", "CTO"],
    tasks: [
      "Direct daily operations of IT or engineering departments",
      "Develop strategic plans for technology investments and staffing",
      "Evaluate vendor proposals and negotiate technology contracts",
      "Present technology roadmaps and budget requests to executive leadership",
      "Ensure compliance with security policies and regulatory requirements",
      "Review project proposals and allocate resources across initiatives",
      "Coach and develop technical managers and senior individual contributors",
    ],
    skills: ["Management of Personnel Resources", "Critical Thinking", "Judgment and Decision Making", "Complex Problem Solving"],
    workActivities: ["Making Decisions and Solving Problems", "Communicating with Supervisors", "Coordinating the Work and Activities of Others"],
  },
  {
    code: "29-1141.00",
    title: "Registered Nurses",
    description: "Assess patient health problems and needs, develop and implement nursing care plans, and maintain medical records.",
    alternateTitles: ["RN", "Clinical Nurse", "Staff Nurse"],
    tasks: [
      "Monitor and record patient symptoms and vital signs",
      "Administer medications and treatments according to physician orders",
      "Educate patients and families on health conditions and care plans",
      "Collaborate with physicians and healthcare teams on patient care",
      "Document patient assessments and interventions in medical records",
      "Perform physical assessments and respond to changes in patient condition",
    ],
    skills: ["Active Listening", "Social Perceptiveness", "Critical Thinking", "Service Orientation"],
    workActivities: ["Assisting and Caring for Others", "Documenting/Recording Information", "Making Decisions and Solving Problems"],
  },
  {
    code: "13-2011.00",
    title: "Accountants and Auditors",
    description: "Examine, analyze, and interpret accounting records to prepare financial statements and give advice.",
    alternateTitles: ["Accountant", "Financial Analyst", "Auditor", "CPA"],
    tasks: [
      "Prepare detailed reports on audit findings and financial statements",
      "Examine records and transactions for compliance with laws and regulations",
      "Analyze financial data to identify trends and recommend improvements",
      "Review accounting systems and internal controls for accuracy",
      "Prepare tax returns and ensure compliance with tax regulations",
      "Reconcile accounts and resolve discrepancies in financial records",
    ],
    skills: ["Mathematics", "Critical Thinking", "Active Listening", "Reading Comprehension"],
    workActivities: ["Processing Information", "Analyzing Data or Information", "Evaluating Information to Determine Compliance"],
  },
  {
    code: "27-1024.00",
    title: "Graphic Designers",
    description: "Design or create graphics to meet specific commercial or promotional needs.",
    alternateTitles: ["Designer", "UX Designer", "Visual Designer", "Creative Director"],
    tasks: [
      "Create designs, concepts, and sample layouts based on knowledge of layout principles",
      "Use computer software to generate new images and design elements",
      "Collaborate with clients or art directors to develop creative concepts",
      "Review final layouts and suggest improvements before production",
      "Prepare illustrations or rough sketches of material for approval",
      "Research design trends and competitor creative approaches",
    ],
    skills: ["Originality", "Fluency of Ideas", "Active Learning", "Critical Thinking"],
    workActivities: ["Thinking Creatively", "Working with Computers", "Getting Information"],
  },
  {
    code: "43-3031.00",
    title: "Bookkeeping, Accounting, and Auditing Clerks",
    description: "Compute, classify, and record numerical data to keep financial records complete.",
    alternateTitles: ["Bookkeeper", "Accounting Clerk", "Finance Coordinator", "Operations Coordinator"],
    tasks: [
      "Operate computers programmed with accounting software to record transactions",
      "Perform routine calculations and produce financial reports",
      "Check figures, postings, and documents for correct entry and mathematical accuracy",
      "Classify and summarize numerical and financial data to compile records",
      "Reconcile bank statements and verify deposits and payments",
      "Process invoices, receipts, and payments according to established procedures",
    ],
    skills: ["Mathematics", "Active Listening", "Reading Comprehension", "Monitoring"],
    workActivities: ["Processing Information", "Performing Administrative Activities", "Documenting/Recording Information"],
  },
  {
    code: "15-1244.00",
    title: "Network and Computer Systems Administrators",
    description: "Install, configure, and maintain an organization's computer systems and networks.",
    alternateTitles: ["Systems Administrator", "Network Administrator", "IT Administrator", "Infrastructure Engineer"],
    tasks: [
      "Maintain and administer computer networks and related computing environments",
      "Diagnose hardware and software problems and replace defective components",
      "Configure and monitor security permissions for users and systems",
      "Perform data backups and disaster recovery operations",
      "Document network configurations and standard operating procedures",
      "Apply patches and updates to operating systems and applications",
    ],
    skills: ["Critical Thinking", "Complex Problem Solving", "Reading Comprehension", "Systems Analysis"],
    workActivities: ["Working with Computers", "Making Decisions and Solving Problems", "Updating and Using Relevant Knowledge"],
  },
];

export function getLocalOccupationByCode(code: string): OnetOccupation | null {
  return LOCAL_ONET_INDEX.find((o) => o.code === code) ?? null;
}
